Document: python-minerva-node-transform
Title: Debian python-minerva-node-transform Manual
Author: <insert document author here>
Abstract: This manual describes what python-minerva-node-transform is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-minerva-node-transform/python-minerva-node-transform.sgml.gz

Format: postscript
Files: /usr/share/doc/python-minerva-node-transform/python-minerva-node-transform.ps.gz

Format: text
Files: /usr/share/doc/python-minerva-node-transform/python-minerva-node-transform.text.gz

Format: HTML
Index: /usr/share/doc/python-minerva-node-transform/html/index.html
Files: /usr/share/doc/python-minerva-node-transform/html/*.html
