Document: minerva-node
Title: Debian minerva-node Manual
Author: <insert document author here>
Abstract: This manual describes what minerva-node is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/minerva-node/minerva-node.sgml.gz

Format: postscript
Files: /usr/share/doc/minerva-node/minerva-node.ps.gz

Format: text
Files: /usr/share/doc/minerva-node/minerva-node.text.gz

Format: HTML
Index: /usr/share/doc/minerva-node/html/index.html
Files: /usr/share/doc/minerva-node/html/*.html
