Document: minerva-dispatcher
Title: Debian minerva-dispatcher Manual
Author: <insert document author here>
Abstract: This manual describes what minerva-dispatcher is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/minerva-dispatcher/minerva-dispatcher.sgml.gz

Format: postscript
Files: /usr/share/doc/minerva-dispatcher/minerva-dispatcher.ps.gz

Format: text
Files: /usr/share/doc/minerva-dispatcher/minerva-dispatcher.text.gz

Format: HTML
Index: /usr/share/doc/minerva-dispatcher/html/index.html
Files: /usr/share/doc/minerva-dispatcher/html/*.html
