Document: python-minerva-node-dummy
Title: Debian python-minerva-node-dummy Manual
Author: <insert document author here>
Abstract: This manual describes what python-minerva-node-dummy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-minerva-node-dummy/python-minerva-node-dummy.sgml.gz

Format: postscript
Files: /usr/share/doc/python-minerva-node-dummy/python-minerva-node-dummy.ps.gz

Format: text
Files: /usr/share/doc/python-minerva-node-dummy/python-minerva-node-dummy.text.gz

Format: HTML
Index: /usr/share/doc/python-minerva-node-dummy/html/index.html
Files: /usr/share/doc/python-minerva-node-dummy/html/*.html
