node ('git') {
    stage ('checkout') {
        checkout scm
    }

    stage ('build') {
        // Report status of stage 'build' back to Gitlab
        gitlabCommitStatus(name: 'build') {
            def buildDir = 'dispatcher/pkg-build'

            // Clean the build directory before starting
            sh "rm -rf ${buildDir}"
            sh "mkdir -p ${buildDir}"

            dir ('dispatcher/debian') {
                sh './make-changelog'
            }

            docker.withRegistry("https://${docker_registry}", 'hitc-docker-registry') {
                docker.image('ubuntu-1604-packaging').inside("-v ${workspace}/dispatcher:/package/source -v ${workspace}/${buildDir}:/package/build") {
                    sh 'package'
                }
            }

            publishPackages buildDir.toString(), 'common/stable', 'xenial'

            archiveArtifacts(artifacts: "${buildDir}/*")
        }
    }
}
