#!/bin/bash
set -e
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

psql -d postgres -c "CREATE DATABASE $MINERVA_DB_NAME;"

$SCRIPT_DIR/install-db-deps
$SCRIPT_DIR/run-db-scripts $MINERVA_DB_SCRIPT_ROOT
