Document: python-minerva-node-harvest
Title: Debian python-minerva-node-harvest Manual
Author: <insert document author here>
Abstract: This manual describes what python-minerva-node-harvest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-minerva-node-harvest/python-minerva-node-harvest.sgml.gz

Format: postscript
Files: /usr/share/doc/python-minerva-node-harvest/python-minerva-node-harvest.ps.gz

Format: text
Files: /usr/share/doc/python-minerva-node-harvest/python-minerva-node-harvest.text.gz

Format: HTML
Index: /usr/share/doc/python-minerva-node-harvest/html/index.html
Files: /usr/share/doc/python-minerva-node-harvest/html/*.html
